branch-defaults:
  master:
    environment: melodymunk-prod
  matt_facebook_login:
    environment: melodymunk-prod
environment-defaults:
  melody-munk:
    branch: null
    repository: null
global:
  application_name: melody-munk
  default_ec2_keyname: null
  default_platform: PHP 7.0
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
