<?php

namespace AppBundle\Repository;

/**
 * List_Has_PermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class List_Has_PermissionRepository extends \Doctrine\ORM\EntityRepository
{
}
