<?php

namespace AppBundle\Repository;

/**
 * Permission_ListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Permission_ListRepository extends \Doctrine\ORM\EntityRepository
{
}
