<?php

namespace AppBundle\Repository;

/**
 * Role_Has_PermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Role_Has_PermissionRepository extends \Doctrine\ORM\EntityRepository
{
}
