<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Role;
use AppBundle\Entity\Room;

/**
 * RoomPermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomPermissionRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * Query Function
     * --------------
     * Returns all the permissions a role has in a room
     *
     * @param Room $room
     * @param Role $role
     * @return array
     */
    public function getPermissionsForRole(Room $room, Role $role) {
        $query = $this->createQueryBuilder('permission')
            ->where('permission.room = :room')
            ->andWhere('permission.role = :role')
            ->getQuery();

        return $query->getResult();
    }
}
