<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Room;
use AppBundle\Entity\User;

/**
 * RoomUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomUserRepository extends \Doctrine\ORM\EntityRepository
{

    public function findRoomUser(User $user, Room $room) {
        $query = $this->createQueryBuilder('room_user')
            ->where('room_user.user = :user')
            ->andWhere('room_user.room = :room')
            ->setParameter('user', $user)
            ->setParameter('room', $room)
            ->orderBy('room_user.dateAdded', 'DESC')
            ->getQuery();

        return $query->getResult();
    }


    public function getRoomUsers(Room $room) {
        $query = $this->createQueryBuilder('room_user')
            ->andWhere('room_user.room = :room')
            ->setParameter('room', $room)
            ->orderBy('room_user.dateAdded', 'DESC')
            ->getQuery();

        return $query->getResult();
    }

}
