<?php

namespace AppBundle\Repository;

/**
 * Room_PermissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Room_PermissionsRepository extends \Doctrine\ORM\EntityRepository
{
}
