<?php

namespace AppBundle\Repository;

/**
 * RoomPermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomPermissionRepository extends \Doctrine\ORM\EntityRepository
{
}
