<?php

namespace AppBundle\Repository;

/**
 * SongRestrictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongRestrictionRepository extends \Doctrine\ORM\EntityRepository
{
}
