<?php

namespace AppBundle\Repository;

/**
 * UserReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserReviewRepository extends \Doctrine\ORM\EntityRepository
{
}
