<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * UserReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserReviewRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * User Review Query
     * -----------------
     * Gets all the user reviews for the user provided into params
     *
     * @param User $user
     * @return array
     */
    public function getAllReviewsForUser(User $user) {

        $query = $this->createQueryBuilder('review')
            ->where('review.user = :user')
            ->setParameter('user', $user)
            ->orderBy('review.dateCreated', 'DESC')
            ->getQuery();


        return $query->getResult();

    }


}
