<?php

namespace AppBundle\Repository;

/**
 * UserListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserListRepository extends \Doctrine\ORM\EntityRepository
{
}
