<?php

namespace AppBundle\Repository;

/**
 * UserAPITokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAPITokenRepository extends \Doctrine\ORM\EntityRepository
{
}
