# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:

        dev:
            pattern:    ^/(_profiler|_wdt|css|js|assets)
            security:   false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
#                csrf_token_generator: security.csrf.token_manager
                require_previous_session: false
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: false
                default_target_path: /
                use_referer: false

            logout:
                path: fos_user_security_logout
                target: /login

            anonymous:    true

            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/join, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/generateqr/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/spotifyintegration/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/callback/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/callback, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/getauthorizeurl/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/play/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pause/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/raisevolume/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/lowervolume/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/nextsong/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/prevsong/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fastforward/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/(.*), role: ROLE_USER }
