# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    # Permissions Service
    melodymunk.permissions:
          class: AppBundle\Service\PermissionService
          arguments: ['@doctrine.orm.entity_manager']


    melodymunk.spotify:
        class: AppBundle\Service\SpotifyService


